plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.nexora'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Librerías indispensables para JWT
	// Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
	// Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl metodos
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	// Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api convertir cifrado de cifrado el encabezado y jlow de un token
	implementation "io.jsonwebtoken:jjwt-api:0.13.0"

	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'com.mysql:mysql-connector-j'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
